use std::collections::BTreeMap;

use axum::http::StatusCode;
use serde_json::Value;

use crate::{
    app::AppState,
    error::AppError,
    schema::{ColumnSchema, ColumnType},
    storage::load_resource,
};

use super::types::SqlExportDialect;

pub(crate) async fn build_sql_export(
    state: &AppState,
    dialect: SqlExportDialect,
) -> Result<String, AppError> {
    let resources = state.resources.read().await.iter().cloned().collect::<Vec<_>>();
    let mut chunks = vec![format!(
        "-- SQL export generated by dirbase\n-- dialect: {}\n-- object resources exported as single-row tables with synthetic id=1\n\n",
        match dialect {
            SqlExportDialect::Postgres => "postgres",
            SqlExportDialect::Sqlite => "sqlite",
        }
    )];
    for resource in resources {
        let data = load_resource(state, &resource).await?;
        append_table_export(&mut chunks, state, &resource, data.as_ref(), dialect)?;
    }
    Ok(chunks.concat())
}

fn append_table_export(
    chunks: &mut Vec<String>,
    state: &AppState,
    resource: &str,
    data: &Value,
    dialect: SqlExportDialect,
) -> Result<(), AppError> {
    let rows = normalize_resource_rows(data)?;
    let columns = resolve_export_columns(state, resource, &rows)?;
    chunks.push(format!("-- Resource: {resource}\n"));
    chunks.push(build_create_table_statement(resource, &columns, dialect));
    for row in rows {
        chunks.push(build_insert_statement(resource, &columns, row, dialect));
    }
    chunks.push("\n".to_string());
    Ok(())
}

fn normalize_resource_rows(data: &Value) -> Result<Vec<BTreeMap<String, Value>>, AppError> {
    match data {
        Value::Array(items) => items
            .iter()
            .map(|item| {
                item.as_object()
                    .ok_or_else(|| {
                        AppError::new(
                            StatusCode::BAD_REQUEST,
                            "Array resource row is not an object",
                        )
                    })
                    .map(|o| {
                        o.iter().map(|(k, v)| (k.clone(), v.clone())).collect::<BTreeMap<_, _>>()
                    })
            })
            .collect(),
        Value::Object(object) => {
            let mut row = BTreeMap::new();
            row.insert("id".to_string(), Value::from(1));
            for (k, v) in object {
                row.insert(k.clone(), v.clone());
            }
            Ok(vec![row])
        }
        _ => Err(AppError::new(
            StatusCode::BAD_REQUEST,
            "Resource must be a JSON array or object for SQL export",
        )),
    }
}

fn resolve_export_columns(
    state: &AppState,
    resource: &str,
    rows: &[BTreeMap<String, Value>],
) -> Result<Vec<(String, ColumnSchema)>, AppError> {
    let schema = state.schema_snapshot();
    if let Some(table) = schema.tables.get(resource) {
        return Ok(table
            .columns
            .iter()
            .map(|(name, schema)| (name.clone(), schema.clone()))
            .collect());
    }
    let mut inferred = BTreeMap::<String, ColumnSchema>::new();
    for row in rows {
        for (key, value) in row {
            let inferred_type = ColumnType::infer_json(value);
            let entry = inferred.entry(key.clone()).or_insert(ColumnSchema {
                column_type: inferred_type.clone().unwrap_or(ColumnType::String),
                nullable: false,
                enum_values: None,
                min: None,
                max: None,
                min_length: None,
                max_length: None,
                pattern: None,
            });
            if let Some(it) = inferred_type
                && entry.column_type != it
            {
                let entry_is_json = matches!(entry.column_type, ColumnType::Json);
                entry.column_type = if matches!(it, ColumnType::Json) || entry_is_json {
                    ColumnType::Json
                } else {
                    ColumnType::String
                };
            }
            if value.is_null() {
                entry.nullable = true;
            }
        }
    }
    for row in rows {
        for (name, column) in &mut inferred {
            if !row.contains_key(name) {
                column.nullable = true;
            }
        }
    }
    Ok(inferred.into_iter().collect())
}

fn build_create_table_statement(
    resource: &str,
    columns: &[(String, ColumnSchema)],
    dialect: SqlExportDialect,
) -> String {
    let defs = columns
        .iter()
        .map(|(name, schema)| {
            format!(
                "  \"{}\" {}{}",
                name,
                dialect.type_name(&schema.column_type),
                if schema.nullable { "" } else { " NOT NULL" }
            )
        })
        .collect::<Vec<_>>()
        .join(",\n");
    format!("CREATE TABLE \"{}\" (\n{}\n);\n", resource, defs)
}

fn build_insert_statement(
    resource: &str,
    columns: &[(String, ColumnSchema)],
    row: BTreeMap<String, Value>,
    dialect: SqlExportDialect,
) -> String {
    let col_sql =
        columns.iter().map(|(name, _)| format!("\"{}\"", name)).collect::<Vec<_>>().join(", ");
    let val_sql = columns
        .iter()
        .map(|(name, schema)| serialize_sql_value(row.get(name), &schema.column_type, dialect))
        .collect::<Vec<_>>()
        .join(", ");
    format!("INSERT INTO \"{}\" ({}) VALUES ({});\n", resource, col_sql, val_sql)
}

fn serialize_sql_value(
    value: Option<&Value>,
    column_type: &ColumnType,
    dialect: SqlExportDialect,
) -> String {
    let Some(value) = value else {
        return "NULL".to_string();
    };
    match value {
        Value::Null => "NULL".to_string(),
        Value::Bool(v) => {
            if *v {
                "TRUE".to_string()
            } else {
                "FALSE".to_string()
            }
        }
        Value::Number(v) => v.to_string(),
        Value::String(v) => quote_sql_string(v),
        Value::Array(_) | Value::Object(_) => {
            let json = serde_json::to_string(value).unwrap_or_else(|_| "null".to_string());
            if matches!(column_type, ColumnType::Json)
                && matches!(dialect, SqlExportDialect::Postgres)
            {
                format!("{}::jsonb", quote_sql_string(&json))
            } else {
                quote_sql_string(&json)
            }
        }
    }
}

fn quote_sql_string(input: &str) -> String {
    format!("'{}'", input.replace('\'', "''"))
}
