name: Rust Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  rust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run tests
        run: |
          rm -rf ui/dist
          DIRBASE_REBUILD_UI=1 cargo test --all-features --verbose -- --test-threads=1
